name: servant-typescript

on:
  pull_request:
  push:
    branches: [main]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc:
        # - "8.6.5"
        # - "8.8.4"
        # - "8.10.7"
        - "9.0.2"
        - "9.2.8"
        - "9.4.8"
        - "9.6.7"
        - "9.8.4"
        - "9.10.2"
        - "9.12.2"
        exclude:
        # These don't work on GitHub CI anymore because they need llvm@13, which became
        # disabled on 12/31/2024
        - os: macOS-latest
          ghc: 8.10.7
        - os: macOS-latest
          ghc: 9.0.2

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"

    - name: Freeze
      run: |
        cabal update
        cabal configure --enable-tests
        cabal freeze

    - uses: actions/cache@v4
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}-key2

    - name: Build
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all

    # - name: Test
    #   run: |
    #     cabal test all

  stack:
    name: ${{ matrix.stack-yaml }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack-yaml:
        - stack-ghc96.yaml
        - stack-ghc98.yaml
        - stack-ghc910.yaml
        - stack-ghc912.yaml

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: "latest"

    - uses: actions/cache@v4
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Run stack setup
      shell: bash
      run: |
        export STACK_EXTRA_ARGS="--stack-yaml ${{matrix.stack-yaml}}"
        stack setup $STACK_EXTRA_ARGS
        echo STACK_EXTRA_ARGS="$STACK_EXTRA_ARGS" >> $GITHUB_ENV

    - name: Build
      run: |
        stack build $STACK_EXTRA_ARGS --test --bench --no-run-tests --no-run-benchmarks

    # - name: Test
    #   run: |
    #     stack test $STACK_EXTRA_ARGS
